echo message are now redirected to stderr instead of stdout

diff --git a/eyamldecrypt b/eyamldecrypt
--- a/eyamldecrypt
+++ b/eyamldecrypt
@@ -8,7 +8,7 @@
 
 # parse args
 usage () {
-  cat <<EOF
+  cat 1>&2 <<EOF
 eyamldecrypt -k|--key <private_key_file> -p|--pub <pkcs_public_key_file> -d|--directory <dir-with-eyml-files>
 
 # environment variables (has priority over params)
@@ -47,28 +47,28 @@ do
 done
 
 # make sure eyaml exists
-command -v eyaml >/dev/null 2>&1 || { echo "Command 'eyaml' does not exist and is required to run this script.  Aborting."; exit 1; }
+command -v eyaml >/dev/null 2>&1 || { echo 1>&2 "Command 'eyaml' does not exist and is required to run this script.  Aborting."; exit 1; }
 
 # load env
 if [ ! -z "${EYAMLDECRYPT_PRIVATE_KEY}" ]
 then
-  echo "Setting private key from environment"
+  echo 1>&2 "Setting private key from environment"
   privateKeyTmpFile=$(mktemp)
-  echo "${EYAMLDECRYPT_PRIVATE_KEY}" > $privateKeyTmpFile
+  echo -n "${EYAMLDECRYPT_PRIVATE_KEY}" > $privateKeyTmpFile
   privateKeyFile=$privateKeyTmpFile
 fi
 
 if [ ! -z "${EYAMLDECRYPT_PUBLIC_KEY}" ]
 then
-  echo "Setting public key from env"
+  echo 1>&2 "Setting public key from env"
   publicKeyTmpFile=$(mktemp)
-  echo "${EYAMLDECRYPT_PUBLIC_KEY}" > $publicKeyTmpFile
+  echo -n "${EYAMLDECRYPT_PUBLIC_KEY}" > $publicKeyTmpFile
   publicKeyFile=$publicKeyTmpFile
 fi
 
 if [ ! -z "${EYAMLDECRYPT_CONF_DIR}" ]
 then
-  echo "Setting directory from env"
+  echo 1>&2 "Setting directory from env"
   configDir="${EYAMLDECRYPT_CONF_DIR}"
 fi
 
@@ -76,19 +76,19 @@ fi
 # validate inputs
 if [ -z $privateKeyFile ] || [ ! -f $privateKeyFile ]
 then
-  echo "Invalid private key file"
+  echo 1>&2 "Invalid private key file"
   usage
 fi
 
 if [ -z $publicKeyFile ] || [ ! -f $publicKeyFile ]
 then
-  echo "Invalid public key file"
+  echo 1>&2 "Invalid public key file"
   usage
 fi
 
 if [ -z $configDir ] || [ ! -d $configDir ]
 then
-  echo "Invalid configuration directory"
+  echo 1>&2 "Invalid configuration directory"
   usage
 fi
 
